
[window]
opacity = 0.9

[font]
size = 12.0

[font.normal]
family = "DejaVuSansM Nerd Font Mono"
style = "Regular"

[font.bold]
family = "DejaVuSansM Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "DejaVuSansM Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "DejaVuSansM Nerd Font Mono"
style = "Italic"

[general]
import = [
    "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

