"""" Editor basic configuration

"" Avoid netrw
let g:loaded_netrw = 1
let g:loaded_netrwPlugin = 1
let g:nvim_tree_auto_close = 1

let mapleader=" "

set mouse=a

set number relativenumber

set wildmode=longest,list,full

filetype plugin on
syntax on

set incsearch
" set hlsearch

set encoding=UTF-8
set expandtab
set shiftwidth=4
set softtabstop=4
set tabstop=4

set splitbelow splitright

set clipboard+=unnamedplus

"""" Remaps

nnoremap ;; :noh<CR>

nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

nnoremap n nzzzv
nnoremap N Nzzzv

"""" Plugin configuration

" vim-plug automatic install
if empty(glob('~/.vim/autoload/plug.vim'))
    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
                \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

call plug#begin()

"" Colorscheme plugin
Plug 'jacoborus/tender.vim'

"" vim-airline plugin
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
let g:airline_theme = 'tender'

"" Devicons plugin
Plug 'ryanoasis/vim-devicons'

"" Nerdtree plugin
Plug 'https://github.com/preservim/nerdtree', { 'on': 'NERDTreeToggle' }
let g:NERDTreeShowHidden = 1
nnoremap <C-n> :NERDTreeToggle<CR>

"" Fuzzy file
Plug 'kien/ctrlp.vim'

"" Comment power
Plug 'scrooloose/nerdcommenter'
let g:NERDCreateDefaultMappings = 0
let g:NERDSpaceDelims = 1

" Toggle comment section or toggle comment on single lines
nnoremap <leader>cc <plug>NERDCommenterToggle
vnoremap gc <plug>NERDCommenterToggle

" Comment block
vnoremap gb <plug>NERDCommenterSexy

"" Autocompletition plugin
" Plug 'ycm-core/YouCompleteMe'

"" LSP
Plug 'prabirshrestha/vim-lsp'
Plug 'mattn/vim-lsp-settings'

call plug#end()

colorscheme tender
