exec-once = LD_PRELOAD=/usr/lib/spotify-adblock.so spotify
exec-once = discord

exec = gsettings set org.gnome.desktop.interface gtk-theme "Adwaita-dark"
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"

env = QT_QPA_PLATFORMTHEME,qt6ct
