# Workspace rules
windowrule = match:class kitty, workspace 1 silent
windowrule = match:class Alacritty, workspace 1 silent
windowrule = match:class Code, workspace 1 silent

windowrule = match:class firefox, workspace 2 silent
windowrule = match:class ^(Microsoft Teams - Preview)$, workspace 3 silent

windowrule = match:class Blender, workspace 4 silent

windowrule = match:class discord, workspace 9 silent

windowrule = match:class spotify, workspace 10 silent
