# i3status configuration file.
# see "man i3status" for documentation.

# It is important that this file is edited as UTF-8.
# The following line should contain a sharp s:
# ß
# If the above line is not correctly displayed, fix your editor first!

general {
        colors = true
        interval = 5
}

order += "wireless _first_"
order += "battery 0"
order += "memory"
order += "volume master"
order += "tztime local"

wireless _first_ {
        format_up = "%essid =>%quality"
        format_down = "Disconnected"
}

battery 0 {
        format = "%status %percentage"
        format_down = "No battery"
        status_chr = "⚡"
        status_bat = "🔋"
        status_unk = "?"
        status_full = "☻"
        status_idle = "☻"
        path = "/sys/class/power_supply/BAT%d/uevent"
        threshold_type = "percentage"
        low_threshold = 20
        color_bad = "#ff0000"
}

volume master {
        format = "♪: %volume"
        format_muted = "♪: muted (%volume)"
        device = "default"
        mixer = "Master"
        mixer_idx = 0
}

memory {
        format = "RAM => %used"
        threshold_degraded = "1G"
        format_degraded = "MEMORY < %available"
}

tztime local {
        format = "%Y-%m-%d %I:%M %p"
}

